Checking arch on build

diff --git a/docker/step-ca-bootstrap/Dockerfile b/docker/step-ca-bootstrap/Dockerfile
--- a/docker/step-ca-bootstrap/Dockerfile
+++ b/docker/step-ca-bootstrap/Dockerfile
@@ -9,9 +9,17 @@ ENV CA_URL="https://127.0.0.1:9000"
 ENV KUBE_LATEST_VERSION="v1.18.2"
 
 USER root
-RUN curl -L https://storage.googleapis.com/kubernetes-release/release/${KUBE_LATEST_VERSION}/bin/linux/arm64/kubectl -o /usr/local/bin/kubectl \
- && chmod +x /usr/local/bin/kubectl
-RUN apk --update add expect
+RUN apk --update add expect && \
+    apkArch="$(apk --print-arch)"; \
+    case "$apkArch" in \
+        armhf) ARCH='arm' ;; \
+        aarch64) ARCH='arm64' ;; \
+        x86_64) ARCH='amd64' ;; \
+        x86) ARCH='386' ;; \
+        *) echo >&2 "error: unsupported architecture: $apkArch"; exit 1 ;; \
+    esac && \
+    curl -L https://storage.googleapis.com/kubernetes-release/release/${KUBE_LATEST_VERSION}/bin/linux/${ARCH}/kubectl -o /usr/local/bin/kubectl && \
+    chmod +x /usr/local/bin/kubectl
 
 COPY entrypoint.sh /home/step/
 RUN chmod +x /home/step/entrypoint.sh
